---
# Только необходимые sysctl настройки (без IPv6)
sysctl:
  net.ipv4.ip_forward: 1
  net.bridge.bridge-nf-call-iptables: 1
  net.bridge.bridge-nf-call-ip6tables: 1
  kernel.panic: 10
  kernel.panic_on_oops: 1
  vm.overcommit_memory: 1
  vm.panic_on_oom: 0

# Отключить проблемные настройки
sysctl_exclude:
  - net.ipv6.conf.all.disable_ipv6
  - net.ipv6.conf.default.disable_ipv6
  - net.ipv6.conf.lo.disable_ipv6
  - kernel.keys.root_maxbytes
  - kernel.keys.root_maxkeys
